const express = require("express");
const router = express.Router();

// Dynamic route generator
const { registerAllModelRoutes } = require("../utils/dynamicRouteGenerator");

const {
  // handleUserSignup,

  // handleUserUpdate,
  // getAllUser,
  // userById,

  // findUserByEmail,

  handleUserLogin,
  handleAdminLogin,
  handleUserSignupCompany,
} = require("../controllers/user");

const {
  productCreate,
  productUpdate,
  productById,
  getAllProducts,
  getAllActiveProducts,
  updateWarehouseQuantity,
  getProductWarehouseInventory,
  checkWarehouseStock,
  getProductsByWarehouse,
  productCreateVariation,
  productUpdateVariation,
  getProductVariationById,
  productDelete,
} = require("../controllers/product");

const { order_save, getOrderByorderItem } = require("../controllers/order");
const {
  checkIntegrationActive,
  syncStoreCategory,
  // syncStoreBrand,
  syncProductRelations,
  syncStoreProduct,
} = require("../controllers/integration");

const { execute_process } = require("../controllers/process");

const {
  apiCreateStockTransfer,
  apiGetStockTransfers,
} = require("../controllers/stockTransfer");

const { purchaseOrderCreate } = require("../controllers/purchase_order");
const { getMyBranches } = require("../controllers/company");
// Note: Blog routes are now handled dynamically by registerAllModelRoutes
// Uncomment these if you need custom routes
// const {
//   blogCreate,
//   blogUpdate,
//   blogById,
//   getAllblog,
//   getallblogactive,
//   blogdelete,
// } = require("../controllers/blog");

// Note: Warehouse routes are now handled dynamically
// const {
//   warehouseCreate,
//   warehouseUpdate,
//   warehouseById,
//   getAllwarehouse,
//   getallwarehouseactive,
//   warehousedelete,
// } = require("../controllers/warehouse");

// Note: Company routes are now handled dynamically
// const {
//   companyCreate,
//   companyUpdate,
//   companyById,
//   getAllcompany,
//   getallcompanyactive,
//   companydelete,
// } = require("../controllers/company");

// Note: Complain routes are now handled dynamically
// const {
//   complainCreate,
//   complainUpdate,
//   complainById,
//   getAllcomplain,
// } = require("../controllers/complain");

// Note: Order and Order Item routes are now handled dynamically
// const {
//   orderCreate,
//   orderUpdate,
//   orderById,
//   getAllorder,
// } = require("../controllers/order");

// const {
//   order_itemCreate,
//   order_itemUpdate,
//   order_itemById,
//   getAllorder_item,
// } = require("../controllers/order_item");

// User routes - Custom auth and management
router.post("/user/user_company", handleUserSignupCompany);
// router.post("/user/create", handleUserSignup);
// router.patch("/user/update/:id", handleUserUpdate);
router.post("/user/login", handleUserLogin);
// router.get("/user/get-all", getAllUser);
// router.get("/user/get/:id", userById);
// router.post("/user/get-one", findUserByEmail);

router.post("/purchase_order/purchase_order_create", purchaseOrderCreate);

// Product routes - Custom CRUD + warehouse inventory management
router.post("/product/create", productCreate);
router.patch("/product/update/:id", productUpdate);
router.get("/product/get/:id", productById);
router.get("/product/get-all", getAllProducts);
router.get("/product/get-all-active", getAllActiveProducts);
router.delete("/product/delete/:id", productDelete);

// Integration routes
router.get("/integration/check-active/:id", checkIntegrationActive);
router.get("/integration/sync-store-category/:id", syncStoreCategory);
// router.get("/integration/sync-store-brand/:id", syncStoreBrand);
router.get("/integration/sync-store-product/:id", syncStoreProduct);
router.get("/integration/find-product-relations/:id", syncProductRelations);

// Process routes
router.get("/process/execute-process", execute_process);

// Company routes
router.get("/company/get-my-branches", getMyBranches);

// Product warehouse inventory management routes
router.patch("/product/:id/warehouse-quantity", updateWarehouseQuantity);
router.get("/product/:id/warehouse-inventory", getProductWarehouseInventory);
router.get("/product/:id/check-stock", checkWarehouseStock);
router.get("/warehouse/:warehouseId/products", getProductsByWarehouse);

// Stock transfer routes
router.get("/stock-transfer", apiGetStockTransfers);
router.post("/stock-transfer", apiCreateStockTransfer);

// Category routes - Custom CRUD
router.post("/product/create-product-variation", productCreateVariation);
router.patch("/product/update-product-variation/:id", productUpdateVariation);
router.get("/product/get-product-variation/:id", getProductVariationById);
// Blog, Integration, Warehouse, Company, Complain, Order, and Order_item routes
// are now automatically generated by registerAllModelRoutes() at the bottom of this file

// Order routes
router.post("/order/order_save", order_save);
router.get("/order/get-order-by-order-item", getOrderByorderItem);

router.post("/test", (req, res) => {
  console.log("Test route hit");
  res.status(200).json({ message: "Test successful" });
});

// Admin routes
router.post("/login/admin", handleAdminLogin);

// Register dynamic CRUD routes for all models
// This automatically creates routes like: /{model}/create, /{model}/update/:id, /{model}/get/:id, etc.
registerAllModelRoutes(router, {
  excludedModels: [
    // User has custom auth routes
    "product", // Product has custom warehouse inventory routes
    "order_item", // Keep custom routes if needed
    "url", // URL has custom routes
    // 'purchase_order' removed - we want BOTH dynamic routes AND custom routes
  ],
  modelConfigs: {
    // You can configure specific models here if needed
    user: {
      enabled: true,
      excludedRoutes: [],
      customRoutes: [],
    },
    blog: {
      enabled: true,
      excludedRoutes: [],
      customRoutes: [],
    },
    integration: {
      enabled: true,
      excludedRoutes: [],
    },
    warehouse: {
      enabled: true,
      excludedRoutes: [],
    },
    company: {
      enabled: true,
      excludedRoutes: [],
    },
    complain: {
      enabled: true,
      excludedRoutes: ["delete"], // Complain doesn't have delete route
    },
    purchase_order: {
      enabled: true,
      excludedRoutes: [],
    },
    category: {
      enabled: true,
      excludedRoutes: [],
    },
    purchase_order_item: {
      enabled: true,
      excludedRoutes: [],
    },
    attribute: {
      enabled: true,
      excludedRoutes: [],
    },
    process: {
      enabled: true,
      excludedRoutes: [],
    },
    brands: {
      enabled: true,
      excludedRoutes: [],
    },
    product_relations: {
      enabled: true,
      excludedRoutes: [],
    },
  },
});

// Add route aliases for category (plural form for backward compatibility)
// These routes forward requests from /category/* to /category/*
const categoryController =
  require("../utils/dynamicRouteGenerator").generateControllerFunctions(
    "category",
  );
// router.patch("/category/update/:id", categoryController.update);
// router.post("/category/create", categoryController.create);
// router.get("/category/get/:id", categoryController.getById);
// router.get("/category/get-all", categoryController.getAll);
// router.get("/category/get-all-active", categoryController.getAllActive);
// router.delete("/category/delete/:id", categoryController.delete);

module.exports = router;
