name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.2

      - name: Sync file
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: 192.249.118.80
          username: pos@testv3.websitedemolynk.com
          password: kYw8,ae@!1&]}dMR

      - name: Restart app on server1
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 192.249.118.80
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 60s
          command_timeout: 10m
          debug: true
          script_stop: true
          script: |
            cd /home/demowebsitv3/public_html/pos_admin
            export PATH="/usr/local/bin:/usr/bin:$PATH"
            which node || true
            which npm || true
            which pm2 || true
            npm install --production
            pm2 restart pos-api || pm2 start index.js --name pos-api
